### ISSUE TITLE
Documentation: Add Jump to next difference shortcuts keybinding option, show on right click

### ISSUE THREAD

**Issue by gitressa** [kaste/Compare-Side-By-Side#3]
To inform that "Jump to next difference" (and previous) shortcuts exist, it would be great if shortcuts keybinding option was added.

POSTPONED: Show shortcuts on right-click in "context"-menu will only be added if and when we find a way to make it only visible when actually in the comparison split-views.

**Comment by gitressa** [comment]
I just saw in the README that next/previous difference shortcut already exists, which is fantastic.

But to make it more easy to discover, it would be great if these two were added: 
- Add shortcuts keybinding option
- Show on right-click

**Comment by kaste** [comment]
The right-click menu is the "context"-menu.  We can only add this if we find a way that it is only visible when actually in the comparison split-views.  I wouldn't want to add this to all views.

**Comment by gitressa** [comment]
Thanks for adding the two shortcuts to the list of shortcuts, after right-click in the split windows.
