### ISSUE TITLE
Could not load colour scheme

### ISSUE THREAD

**Issue by arcticpinecone** [kaste/Compare-Side-By-Side#4]
Hello, and it's great to see this in development again.

Ever since I started using this package, I get this error message:
> Could not load colour scheme.
> Falling back to a blank colour scheme.
> To fix this, please manually re-select your colour scheme in Preferences > Color Scheme
> This should not happen again once action has been taken. 
> Sorry for the inconvenience.

I use the Default Dark theme, and I have also tried setting the 'Select Color Scheme...' and setting it to simply 'Auto'. 
I prefer to use Monokai Pro if I can, but I changed it to try and fix this option. 

Unfortunately, the behavior continues no matter what I have tried so far, and thus, every time I compare, it errors, and then finally comes to the basic black on white 🤐

Thank you again for developing this, and appreciate any possible help. If you need anything from me let me know.

**Comment by arcticpinecone** [comment]
Just wanted to say thank you for such a fast fix! It is sincerely appreciated! 🙏

**Comment by LouDnl** [comment]
This came rather unexpected... I get that you changed the way the colors are handled, but for the life of me I cannot get them back to the ones they were. 
Before coming to this repo and having to dig through issues and commits to find out that you changed the way colors are handled I thought something was wrong with Sublime as it's impossible to see the diff colors in their low brightness way they are.

I tried changing the the settings first.
![image](https://github.com/kaste/Compare-Side-By-Side/assets/8543038/da0fe415-e7e1-4ac9-a573-4458fec0ea26)

And these settings, but nothing is changing:
![image](https://github.com/kaste/Compare-Side-By-Side/assets/8543038/bc116374-08c3-46e3-80b4-cf564166239f)

Absolutely unreadable:
![image](https://github.com/kaste/Compare-Side-By-Side/assets/8543038/eee4ef0c-4f48-48c0-a94e-0fb8630a27f5)

**Comment by LouDnl** [comment]
Took me a while, but I figured it out. Might be a good idea to give an example in the README. Here's mine:
```json
// Documentation at https://www.sublimetext.com/docs/color_schemes.html
{
	"variables":
	{

	},
	"globals":
	{

	},
	"rules":
	[
        {
            "scope": "diff.deleted.sbs-compare",
            "background": "hsla(360, 60%, 60%, 0.55)",
            "foreground_adjust": "l(+ 5%)"
        },
        {
            "scope": "diff.deleted.char.sbs-compare",
            "background": "hsla(360, 80%, 60%, 0.90)",
            "foreground_adjust": "l(+ 10%)"
        },
        {
            "scope": "diff.inserted.sbs-compare",
            "background": "hsla(180, 60%, 60%, 0.35)",
            "foreground_adjust": "l(+ 5%)"
        },
        {
            "scope": "diff.inserted.char.sbs-compare",
            "background": "hsla(180, 45%, 60%, 0.70)",
            "foreground_adjust": "l(+ 10%)"
        }
	]
}

```

**Comment by kaste** [comment]
I have these defaults in my scheme:

![image](https://github.com/kaste/Compare-Side-By-Side/assets/8558/c09594e3-f5f7-454f-92f7-d0c03856ad1a)

which is not as bright as before but totally readable and okay.  

But ... by using standard selector mechanics you were able to define an alpha channel and `foreground_adjust`. That should give you more flexibility on the look than before. 🤔
